[package]
name = "concurrency"
version = "0.1.3"
description = '''This exist to prove a point'''

license = "Apache-2.0"
authors = ["The Surgeon"]
homepage = "https://deadly.surgery"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
